version: '3.5'
services:
  dhcpd:
    build:
      context: ./dhcpd
    restart: always
    network_mode: "host"
    env_file:
      - environments.env
    volumes:
      - dhcp:/dhcpd/
    command: "br0"
  unbound:
    container_name: unbound
    restart: always
    network_mode: "host"
    env_file:
      - environments.env
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "853:853/udp"
#      - "853:853/tcp"
    volumes:
      - dhcp:/dhcpd/
      - certificates:/etc/certificates/
      - ./unbound-conf:/unbound-conf
    build:
      context: ./unbound
volumes:
  certificates:
    name: certificates
    external: true
  unbound-conf:
    name: unbound-conf
  dhcp:
    name: unbound-dhcp
