version: '3.5'
services:
  dhcpd_to_unbound:
    restart: always
    build:
      context: ./dhcpd_to_unbound
    volumes:
      - dhcp:/data
      - unbound-conf:/unbound.conf.d/
    environment:
      DHCPD_LEASES: "/data/dhcpd.leases"
      LOCALDOMAIN: "juniorfox.net"
  dhcpd:
    restart: always
    build:
      context: ./dhcpd
    network_mode: "host"
    volumes:
      - dhcp:/data
    command: "br0"
  unbound:
    container_name: unbound
    restart: always
    network_mode: "host"
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "853:853/udp"
#      - "853:853/tcp"
    volumes:
      - certificates:/etc/certificates/
      - unbound-conf:/etc/unbound/unbound.conf.d/
    build:
      context: ./unbound
volumes:
  certificates:
    name: certificates
    external: true
  unbound-conf:
    name: unbound-conf
  dhcp:
    name: unbound-dhcp
