version: '3.5'
volumes:
  certificates:
    name: certbot-certificates
  unbound-conf:
    name: unbound-conf
services:
  unbound:
    container_name: unbound
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/udp"
      - "853:853/tcp"
    volumes:
      - certificates:/etc/certificates/
    image: cjuniorfox/unbound
