apiVersion: v1
kind: Pod
metadata:
  name: unbound
  labels:
    app: unbound
spec:
  automountServiceAccountToken: false
  containers:
    - name: server
      image: cjuniorfox/unbound:1.20.0
      resources:
        limits:
          memory: 200Mi
          ephemeral-storage: "1Gi"
        requests:
          cpu: 0.5
          memory: 100Mi
          ephemeral-storage: "500Mi"
      env:
        - name: DOMAIN
          value: "juniorfox.net"
      ports:
        - containerPort: 53
          protocol: UDP
          hostPort: 53
          hostIP: 10.1.1.62
        - containerPort: 53
          protocol: UDP
          hostPort: 53
          hostIP: 192.168.3.1
        - containerPort: 853
          protocol: TCP
          hostPort: 853
      volumeMounts:
        - name: dhcp-volume
          mountPath: /dhcpd
        - name: unbound-conf-volume
          mountPath: /unbound-conf
        - name: certificates-pvc
          mountPath: /etc/certificates
        - name: unbound-conf-d-pvc
          mountPath: /etc/unbound/unbound.conf.d
  restartPolicy: Always
  volumes:
    - name: dhcp-volume
      hostPath:
        path: /var/lib/dhcp/
    - name: unbound-conf-volume
      hostPath:
        path: /usr/local/src/podman/unbound/kubernetes/volumes/unbound-conf/ 
    - name: certificates-pvc
      persistentVolumeClaim:
        claimName: certificates
    - name: unbound-conf-d-pvc
      persistentVolumeClaim:
        claimName: unbound-conf
  networks:
    - name: unbound-net
      ipam:
        config:
          ip: 10.89.10.100
---
apiVersion: v1
kind: Network
metadata:
  name: unbound-net
spec:
  plugins:
    - name: bridge
      ipam:
        config:
          - subnet: 10.89.10.96/28
            gateway: 10.89.10.97
            ipRange: 10.89.10.98/28
