name: Build, Tag, and Publish Unbound Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight (UTC)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/unbound:latest ./unbound

      # Extract Unbound version
      - name: Get Unbound Version
        id: unbound_version
        run: |
          version=$(docker run --rm ${{ secrets.DOCKER_USERNAME }}/unbound:latest unbound -V)
          echo "Unbound version: $version"
          echo "UNBOUND_VERSION=$version" >> $GITHUB_ENV

      # Tag the Docker image with the Unbound version
      - name: Tag Docker Image
        run: |
          version=$(echo "${{ env.UNBOUND_VERSION }}" | grep -oP 'unbound \[\K[0-9]+\.[0-9]+\.[0-9]+')
          if [ -n "$version" ]; then
            docker tag ${{ secrets.DOCKER_USERNAME }}/unbound:latest ${{ secrets.DOCKER_USERNAME }}/unbound:$version
            echo "Tagged image with version: $version"
          else
            echo "Version extraction failed!"
          fi

      # Push both the latest and version-tagged Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/unbound:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/unbound:${{ steps.unbound_version.outputs.VERSION }}

